# Generated by Django 5.1.3 on 2025-01-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
