# Generated by Django 5.1.4 on 2025-01-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type2',
            old_name='paretnt',
            new_name='parent',
        ),
    ]
