# Generated by Django 5.1.4 on 2025-01-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_rename_paretnt_type2_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'level one category'), (2, 'level two category'), (3, 'level three category'), (4, 'level four category')])),
                ('parent_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='ecomm.category')),
            ],
        ),
    ]
